name: Unit Test

on: [push]

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run tests
        run: python setup.py test
