name: CI

on: [push]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pipenv install --dev
          pytest -s start

