name: CI

on: [push]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: docker://python:3.7-slim
        run: |
          pipenv install --dev
          pytest -s start

